### ISSUE TITLE
Улучшить форму

### ISSUE THREAD

**Issue by AlexeyPogorelov** [navernoedenis/test-table#11]
https://github.com/navernoedenis/test-table/blob/4c41e6b0e6b0041c51af1c6fc9bb9cae0714e75b/src/components/table/table-modal/table-modal.component.jsx#L51

Много свойств повторяется. Сделай это циклом. Массив с опциями будет лучшим решением

**Comment by navernoedenis** [comment]
Решил явно передать параметры. Без рест-оператора.
